### ISSUE TITLE
No way to flush multiline events

### ISSUE THREAD

**Issue by dpratt** [okkez/fluent-plugin-concat#1]
There's no way to specify a flush interval, which means that a multiline event is only ever delivered after the next event is delivered. This can cause some headaches in production - if you log a multiline error, fluentd won't output it until at least one more message has been logged.

For example, the following config and input will hang forever with no output 

```
<source>
  type tail
  path /var/log/*.log
  pos_file /var/log/varlog.log.pos
  format json
  tag jsonlog.*
  read_from_head true
</source>

<filter jsonlog.**>
  @type concat
  key log
  stream_identity_key container_id
  multiline_start_regexp /^\S+/
</filter>

<match **>
  type stdout
</match>
```

```
{"log":"Error connecting to database...","stream":"stdout","time":"2016-04-15T19:25:46.655449074Z", "container_id": "1234"}
{"log":"  sadly this stacktrace","stream":"stdout","time":"2016-04-15T19:25:46.655490401Z", "container_id": "1234"}
{"log":"  and associated error message","stream":"stdout","time":"2016-04-15T19:25:46.655498254Z", "container_id": "1234"}
{"log":"  will not be delivered for an indeterminate time","stream":"stdout","time":"2016-04-15T19:25:46.65550259Z", "container_id": "1234"}
```

Some sort of background job should run through all the in-flight multiline buffers and flush them after a timeout has expired.

**Comment by okkez** [comment]
Thank you for reporting issue.
I think this is very important issue.
I will try to fix this issue in next week.

**Comment by okkez** [comment]
Support flush interval and release v0.4.0!
@dpratt please try it!
