### ISSUE TITLE
Multi-line message should keep timestamp of first line

### ISSUE THREAD

**Issue by macdjord** [okkez/fluent-plugin-concat#10]
If multiple lines are concatenated, the resulting event should have the timestamp of the _first_ event in that list, not the last. Similarly, if an event is emitted due to timeout, it should carry the timestamp of the first element, not the time at which the timeout occurred.

**Comment by okkez** [comment]
Why do you think so?
Could you describe the reason?

**Comment by macdjord** [comment]
For multi-line log entries, often the only line that contains an embedded timestamp is the first one. (Indeed, often the way I parse things is by assuming that anything that starts with a timestamp is a new log entry, and anything that doesn't is a continuation). This means that the only line that has the correct timestamp is the first one - the rest have the timestamp of when they were read in, which might not be the same one.

For timeouts, it's even simple: A line comes in at 12:00:00. It gets processed, held, and after X seconds the timeout expires and it gets sent on. It now carries a timestamp of 12:00:X. This timestamp is _wrong_; the log entry happened at 12:00:00.

**Comment by okkez** [comment]
Thank you for describing reason.
I will work for this issue in next week.
