### ISSUE TITLE
n_lines

### ISSUE THREAD

**Issue by fahimeh2010** [okkez/fluent-plugin-concat#18]
Hello
is it possible to set n_lines at least n times? because for some logs for example mysql-slow log there are different number of lines in each log.
Thanks a lot

**Comment by okkez** [comment]
Use `multiline_start_regexp` ad `multiline_end_regexp` for that purpose.
BTW, mysql slow query log can be saved in the mysql table, and how about fluent-plugin-sql's in_sql?

**Comment by fahimeh2010** [comment]
Consider these two line of logs
```
# Time: 160820  0:16:23
# User@Host: foo @foo []  Id: 1358
# Schema: foo  Last_errno: 0  Killed: 0
# Query_time: 1.8986  Lock_time: 0.000037  Rows_sent: 0  Rows_examined: 1  Rows_affected: 0
# Bytes_sent: 52
use hodhod;
SET timestamp=14720;
UPDATE foo SET foo='foo'
WHERE  (id = '15');
```

```
# Time: 160825 10:16:02
# User@Host: foo @ foo []  Id: 12105
# Schema: foo  Last_errno: 0  Killed: 0
# Query_time: 1.8751  Lock_time: 0.000022  Rows_sent: 0  Rows_examined: 124594  Rows_affected: 9
# Bytes_sent: 11
SET timestamp=143962;
INSERT INTO foo (....)
```
what I must set in ```multiline_start_regexp``` and ```multiline_end_regexp```?

Thanks a lot

**Comment by okkez** [comment]
Maybe,

```
multiline_start_regexp /# Time:/
multiline_end_regexp /^(?!SET timestamp).+;?$/
```

**Comment by fahimeh2010** [comment]
actually first log have 9 lines, each of these include (SET timestamp=14720;\nUPDATE foo SET foo='foo'\nWHERE  (id = '15');) is one line of log. the last line is ```WHERE  (id = '15');```


second log have 7 lines. the last line is ```INSERT INTO foo (....);```

**Comment by okkez** [comment]
Could you describe your full configuration?
I cannot imagine your situation at all.

**Comment by fahimeh2010** [comment]
```
# Time: 160820  0:16:23
# User@Host: foo @foo []  Id: 1358
# Schema: foo  Last_errno: 0  Killed: 0
# Query_time: 1.8986  Lock_time: 0.000037  Rows_sent: 0  Rows_examined: 1  Rows_affected: 0
# Bytes_sent: 52
use hodhod;
SET timestamp=14720;
UPDATE foo SET foo='foo'
WHERE  (id = '15');
```
above log has 9 lines.


```
# Time: 160825 10:16:02
# User@Host: foo @ foo []  Id: 12105
# Schema: foo  Last_errno: 0  Killed: 0
# Query_time: 1.8751  Lock_time: 0.000022  Rows_sent: 0  Rows_examined: 124594  Rows_affected: 9
# Bytes_sent: 11
SET timestamp=143962;
INSERT INTO foo (....)
```
and this one has 7 lines.

now how can I write a proper configuration that include both of these 2 logs in cocat plugin?

Thanks a lot

**Comment by okkez** [comment]
So what? Could you describe your full configuration? Nothing?

BTW, mysql slow query log can be saved in the mysql table, and how about fluent-plugin-sql's in_sql?

It is very difficult to write proper configuration without full configuration and all patterns of logs.

**Comment by okkez** [comment]
No response.
