### ISSUE TITLE
Timeout flush [dump an error event]

### ISSUE THREAD

**Issue by mpas** [okkez/fluent-plugin-concat#2]
I am testing a simple setup to concat multiple log events being the output of a docker container running a Java program.

The setup is very simple:
Java App (Docker) ----> FluentD (Docker) [output to console]

When I intentionally throw an error inside the Java App the logs are send to FluentD but on certain moments I am getting an error which I can not explain.

Error message:
`2016-05-26 13:35:59 +0000 [warn]: dump an error event: error_class=Fluent::ConcatFilter::TimeoutError error="Timeout flush: ...... etc`

_**The result of this error is that the original log message cannot be parsed.**_

```
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter *.docker.*>
  @type concat
  key log
  stream_identity_key container_id
  multiline_start_regexp /^\S+/
  flush_interval 5s
</filter>

<match **>
    @type stdout
</match>
```

Any suggestion how this can be solved?

**Comment by okkez** [comment]
In this configuration, fluent-plugin-concat flushes all buffer each 5sec (flush_interval) if events does not match `multiline_start_regexp`.

For details:

A event occurs for each second.

### timeout

1. event {message: "MATCH multiline_start_regexp"
1. event {message: "NOT MATCH multiline_start_regexp"
1. event {message: "NOT MATCH multiline_start_regexp"
1. event {message: "NOT MATCH multiline_start_regexp"
1. event {message: "NOT MATCH multiline_start_regexp"
* 5 seconds elapsed: flush fluent-plugin-concat internal buffer(5lines), emit error event and log timeout error

### not timeout

1. event {message: "MATCH multiline_start_regexp"
1. event {message: "NOT MATCH multiline_start_regexp"
1. event {message: "NOT MATCH multiline_start_regexp"
1. event {message: "NOT MATCH multiline_start_regexp"
1. event {message: "MATCH multiline_start_regexp"
  * flush fluent-plugin-concat internal buffer (4lines) and reset interval

**Comment by mpas** [comment]
I my case it seems that some similar log messages are actually concatenated correctly but some not. But these log messages are almost similar.

Example: wich is ok
```
Caused by: java.net.UnknownHostException: dummy-db
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:121)
	... 97 common frames omitted
```

Example: on which i get an error
```
Caused by: java.net.UnknownHostException: dummy-db
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:61)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:121)
	... 89 common frames omitted
```

These are offcourse part of a bigger log-stream but i am lost in why i get an error.
2016-05-30 18:34:24 +0000 [warn]: dump an error event: error_class=Fluent::ConcatFilter::TimeoutError error="Timeout flush: ...

Any clue or hint on how i can get to know the reason why these messages are not concatenated ok?

**Comment by okkez** [comment]
For example. 1st Java exception is raised at 00:00:00, then 2nd Java exception is raised at 00:00:06 (after flush_interval).
You get concatenated 1st Java exception's logs.
2nd Java exception's logs are not concatenated and occured timeout error because 3rd Java exception has not been raised.

You cannot get concatenated log for each Java exception when you use `multiline_start_regexp` only.
You can get concatenated log for each Java exception when use both `multiline_start_regexp` and `multiline_end_regexp`.
