### ISSUE TITLE
Does not handle line which matches both multiline_start_regexp and multiline_end_regexp

### ISSUE THREAD

**Issue by macdjord** [okkez/fluent-plugin-concat#9]
If an incoming line matches both the start and end regexes, it should be emitted immediately as a single-line entry. Currently, it is only treated as a start line, and the fact that it is also an end line is ignored.

**Comment by okkez** [comment]
It is spec of this plugin.

If you want to change spec, you can describe use case.

**Comment by macdjord** [comment]
This works:

    2016-08-17 12:41:06 [info]: Search complete; matches found: [
    187665,
    223211,
    98736]

This doesn't:

    2016-08-17 08:08:52 [info]: Search complete; matches found: [ ]

**Comment by okkez** [comment]
Thank you for describing.
I understand issue.

I will work for this in next week.
